import AppKit
import CryptoKit
import Foundation

/// Turns a pasteboard snapshot into a `CapturedClip` (type detection, hashing).
@MainActor
enum ContentParser {
    /// Pasteboard types that mark content as non-capturable: transient,
    /// auto-generated, concealed, or an explicit third-party opt-out.
    ///
    /// Internal (not private) so the test suite can iterate the real set —
    /// a test that hard-codes one marker silently stops covering the rest
    /// the moment a line is deleted. `ConcealedType` in particular is the
    /// marker password managers actually set, i.e. the primary defence.
    nonisolated static let excludedTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("com.typeit4me.clipping"),
    ]

    /// Parse the given pasteboard into a clip, or nil when there is nothing
    /// worth capturing (empty / unsupported content).
    static func parse(_ pasteboard: NSPasteboard) -> CapturedClip? {
        // 1. Respect opt-out markers (password managers, transient copies, …).
        if let types = pasteboard.types, types.contains(where: excludedTypes.contains) {
            return nil
        }

        // 2. File URLs.
        let urlOptions: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: urlOptions) as? [URL],
           !urls.isEmpty {
            let strings = urls.map(\.absoluteString)
            return CapturedClip(
                kind: .file,
                text: nil,
                richTextData: nil,
                imageData: nil,
                fileURLStrings: strings,
                colorHex: nil,
                hash: hashText("file:" + strings.joined(separator: "\n"))
            )
        }

        // 3. Native color (e.g. copied from a color well / design app).
        if let color = NSColor(from: pasteboard)?.usingColorSpace(.sRGB) {
            let hex = String(
                format: "#%02X%02X%02X",
                Int((color.redComponent * 255).rounded()),
                Int((color.greenComponent * 255).rounded()),
                Int((color.blueComponent * 255).rounded())
            )
            return CapturedClip(
                kind: .color,
                text: hex,
                richTextData: nil,
                imageData: nil,
                fileURLStrings: [],
                colorHex: hex,
                hash: hashText("color:" + hex)
            )
        }

        // 4. Image.
        if let image = NSImage(pasteboard: pasteboard), let data = imageData(for: image) {
            return CapturedClip(
                kind: .image,
                text: nil,
                richTextData: nil,
                imageData: data,
                fileURLStrings: [],
                colorHex: nil,
                hash: hashData(data)
            )
        }

        // 5. Rich text (RTF).
        if let rtf = pasteboard.data(forType: .rtf) {
            let text = pasteboard.string(forType: .string)
                ?? NSAttributedString(rtf: rtf, documentAttributes: nil)?.string
                ?? ""
            return CapturedClip(
                kind: .richText,
                text: text,
                richTextData: rtf,
                imageData: nil,
                fileURLStrings: [],
                colorHex: nil,
                hash: hashData(rtf)
            )
        }

        // 6. Plain string (with hex-color and web-URL refinement).
        guard let string = pasteboard.string(forType: .string) else { return nil }
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty { return nil }

        if let hex = hexColor(in: trimmed) {
            return CapturedClip(
                kind: .color,
                text: hex,
                richTextData: nil,
                imageData: nil,
                fileURLStrings: [],
                colorHex: hex,
                hash: hashText("color:" + hex)
            )
        }

        if isWebURL(trimmed) {
            return CapturedClip(
                kind: .link,
                text: trimmed,
                richTextData: nil,
                imageData: nil,
                fileURLStrings: [],
                colorHex: nil,
                hash: hashText("link:" + trimmed)
            )
        }

        return CapturedClip(
            kind: .text,
            text: string,
            richTextData: nil,
            imageData: nil,
            fileURLStrings: [],
            colorHex: nil,
            hash: hashText("text:" + string)
        )
    }

    /// Detect a hex color literal (e.g. "#ff0000", "#AABBCCDD") inside a string.
    static func hexColor(in string: String) -> String? {
        guard string.hasPrefix("#") else { return nil }
        let digits = string.dropFirst()
        guard digits.count == 6 || digits.count == 8 else { return nil }
        guard digits.allSatisfy(\.isHexDigit) else { return nil }
        return "#" + digits.uppercased()
    }

    /// True when the string looks like a web URL (http/https).
    ///
    /// `nonisolated` so non-MainActor callers (e.g. TextDetector, which
    /// currently hand-duplicates this logic) can share this one copy.
    nonisolated static func isWebURL(_ string: String) -> Bool {
        guard !string.contains(" "), !string.contains("\n") else { return false }
        // "www.example.com" has no scheme; prepend one for validation only.
        let candidate = string.lowercased().hasPrefix("www.") ? "https://" + string : string
        guard let url = URL(string: candidate) else { return false }
        let scheme = url.scheme?.lowercased()
        guard scheme == "http" || scheme == "https" else { return false }
        guard let host = url.host, host.contains(".") else { return false }
        return true
    }

    /// Encode an NSImage as portable image data (PNG preferred).
    static func imageData(for image: NSImage) -> Data? {
        guard let tiff = image.tiffRepresentation else { return nil }
        if let rep = NSBitmapImageRep(data: tiff), let png = rep.representation(using: .png, properties: [:]) {
            return png
        }
        return tiff
    }

    /// Stable hash for text payloads.
    static func hashText(_ string: String) -> String {
        hashData(Data(string.utf8))
    }

    /// Stable hash for binary payloads (SHA-256 hex).
    static func hashData(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}
