import AppKit
import CryptoKit
import Foundation
import ImageIO
import OSLog

/// Turns a pasteboard snapshot into a `CapturedClip` (type detection, hashing).
@MainActor
enum ContentParser {
    /// Pasteboard types that mark content as non-capturable: transient,
    /// auto-generated, concealed, or an explicit third-party opt-out.
    ///
    /// Internal (not private) so the test suite can iterate the real set —
    /// a test that hard-codes one marker silently stops covering the rest
    /// the moment a line is deleted. `ConcealedType` in particular is the
    /// marker password managers actually set, i.e. the primary defence.
    nonisolated static let excludedTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("com.typeit4me.clipping"),
    ]

    /// Parse the given pasteboard into a clip, or nil when there is nothing
    /// worth capturing (empty / unsupported content).
    static func parse(_ pasteboard: NSPasteboard) -> CapturedClip? {
        // 1. Respect opt-out markers (password managers, transient copies, …).
        if let types = pasteboard.types, types.contains(where: excludedTypes.contains) {
            return nil
        }

        // 2. File URLs.
        let urlOptions: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: urlOptions) as? [URL],
           !urls.isEmpty {
            let strings = urls.map(\.absoluteString)
            return CapturedClip(
                kind: .file,
                text: nil,
                richTextData: nil,
                imageData: nil,
                fileURLStrings: strings,
                colorHex: nil,
                hash: hashText("file:" + strings.joined(separator: "\n"))
            )
        }

        // 3. Native color (e.g. copied from a color well / design app).
        if let color = NSColor(from: pasteboard)?.usingColorSpace(.sRGB) {
            let hex = String(
                format: "#%02X%02X%02X",
                Int((color.redComponent * 255).rounded()),
                Int((color.greenComponent * 255).rounded()),
                Int((color.blueComponent * 255).rounded())
            )
            return CapturedClip(
                kind: .color,
                text: hex,
                richTextData: nil,
                imageData: nil,
                fileURLStrings: [],
                colorHex: hex,
                hash: hashText("color:" + hex)
            )
        }

        // 4. Image.
        if let data = imageData(from: pasteboard) {
            return CapturedClip(
                kind: .image,
                text: nil,
                richTextData: nil,
                imageData: data,
                fileURLStrings: [],
                colorHex: nil,
                hash: hashData(data)
            )
        }

        // 5. Rich text (RTF).
        //
        // A hyperlink copied out of a browser page, a share sheet or any rich
        // editor arrives as RTF alongside the plain string. When that string
        // is on its own a bare web URL, it is a link the user copied, not a
        // rich-text document, so step 6 takes it and cleans it.
        if let rtf = pasteboard.data(forType: .rtf), !plainStringIsBareWebURL(pasteboard) {
            let text = pasteboard.string(forType: .string)
                ?? NSAttributedString(rtf: rtf, documentAttributes: nil)?.string
                ?? ""
            return CapturedClip(
                kind: .richText,
                text: text,
                richTextData: rtf,
                imageData: nil,
                fileURLStrings: [],
                colorHex: nil,
                hash: hashData(rtf)
            )
        }

        // 6. Plain string (with hex-color and web-URL refinement).
        guard let string = pasteboard.string(forType: .string) else { return nil }
        return parseText(string)
    }

    /// Parse a bare string the same way a copied one is: a hex colour when it
    /// spells one, a link when it is a web URL, plain text otherwise.
    ///
    /// Edited clips come back through this too: saving an edit has no
    /// pasteboard to parse, so the same rules run on the edited string
    /// itself. Returns nil for an empty or whitespace-only string, the one
    /// input a copy would never have produced.
    static func parseText(_ string: String) -> CapturedClip? {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty { return nil }

        if let hex = hexColor(in: trimmed) {
            return CapturedClip(
                kind: .color,
                text: hex,
                richTextData: nil,
                imageData: nil,
                fileURLStrings: [],
                colorHex: hex,
                hash: hashText("color:" + hex)
            )
        }

        if isWebURL(trimmed) {
            // The stored text is the cleaned URL and the hash follows it, so
            // two copies of the same link carrying different tracking
            // identifiers deduplicate to one clip. `PasteboardWatcher` puts
            // the cleaned URL back on the pasteboard the copy came from.
            let cleaned = LinkSettings.cleanOnCapture(trimmed)
            let text = cleaned?.url ?? trimmed
            return CapturedClip(
                kind: .link,
                text: text,
                richTextData: nil,
                imageData: nil,
                fileURLStrings: [],
                colorHex: nil,
                hash: hashText("link:" + text),
                originalText: cleaned == nil ? nil : trimmed
            )
        }

        return CapturedClip(
            kind: .text,
            text: string,
            richTextData: nil,
            imageData: nil,
            fileURLStrings: [],
            colorHex: nil,
            hash: hashText("text:" + string)
        )
    }

    /// True when the pasteboard's plain string, trimmed, is a bare web URL.
    private static func plainStringIsBareWebURL(_ pasteboard: NSPasteboard) -> Bool {
        guard let string = pasteboard.string(forType: .string) else { return false }
        return isWebURL(string.trimmingCharacters(in: .whitespacesAndNewlines))
    }

    /// Detect a hex color literal (e.g. "#ff0000", "#AABBCCDD") inside a string.
    static func hexColor(in string: String) -> String? {
        guard string.hasPrefix("#") else { return nil }
        let digits = string.dropFirst()
        guard digits.count == 6 || digits.count == 8 else { return nil }
        guard digits.allSatisfy(\.isHexDigit) else { return nil }
        return "#" + digits.uppercased()
    }

    /// True when the string looks like a web URL (http/https).
    ///
    /// `nonisolated` so non-MainActor callers (e.g. TextDetector, which
    /// currently hand-duplicates this logic) can share this one copy.
    nonisolated static func isWebURL(_ string: String) -> Bool {
        guard !string.contains(" "), !string.contains("\n") else { return false }
        // "www.example.com" has no scheme; prepend one for validation only.
        let candidate = string.lowercased().hasPrefix("www.") ? "https://" + string : string
        guard let url = URL(string: candidate) else { return false }
        let scheme = url.scheme?.lowercased()
        guard scheme == "http" || scheme == "https" else { return false }
        guard let host = url.host, host.contains(".") else { return false }
        return true
    }

    /// The largest image payload a clip may hold, in encoded bytes.
    ///
    /// A pasteboard image is unbounded in theory — a photo-library export
    /// can offer hundreds of megabytes — while a clipboard manager's rows
    /// are small by design. 64 MB is far past any screenshot (a 5K full
    /// display is ~15 MB PNG); bigger content is a photo, and a photo is
    /// better handled as the file it usually also is on the board.
    static let maxImageBytes = 64 * 1024 * 1024

    /// The largest image a clip may hold, in pixels. Read from the header
    /// alone — no bitmap decode — so the check costs a few hundred bytes of
    /// the payload it guards.
    static let maxImagePixels = 128_000_000

    /// Encoded representations to take straight off the pasteboard, in
    /// preference order. An image the source app already encoded needs no
    /// TIFF decode and no PNG re-encode — the two costs the old
    /// `NSImage` path paid on every capture, on the main actor.
    static let preferredImageTypes: [NSPasteboard.PasteboardType] = [
        .png,
        .tiff,
        NSPasteboard.PasteboardType("public.jpeg"),
        NSPasteboard.PasteboardType("com.compuserve.gif"),
    ]

    /// The clip's image bytes from a pasteboard, or nil when there is no
    /// usable image. Prefers the encoded representations the source app
    /// already wrote (`preferredImageTypes`); falls back to decoding an
    /// `NSImage` snapshot only when none are offered. Everything is bound
    /// by `maxImageBytes`/`maxImagePixels`: oversized content is skipped
    /// with a notice rather than captured at whatever cost it asks.
    static func imageData(from pasteboard: NSPasteboard) -> Data? {
        for type in preferredImageTypes {
            if let data = pasteboard.data(forType: type), !data.isEmpty {
                return boundedImageData(data)
            }
        }
        guard let image = NSImage(pasteboard: pasteboard),
              let data = imageData(for: image)
        else { return nil }
        return boundedImageData(data)
    }

    /// `data` if it fits the capture budget, nil (with a log line) when it
    /// does not. The pixel read is header-only — ImageIO answers without
    /// decoding the bitmap.
    private static func boundedImageData(_ data: Data) -> Data? {
        guard data.count <= maxImageBytes else {
            log.notice("Image clip skipped: payload over the \(maxImageBytes, privacy: .public)-byte cap")
            return nil
        }
        if let size = pixelSize(of: data), size.pixels > maxImagePixels {
            log.notice("Image clip skipped: \(size.pixels, privacy: .public) pixels over the cap")
            return nil
        }
        return data
    }

    /// Pixel dimensions from an encoded image's header, or nil when the
    /// data does not declare them — which is tolerated rather than fatal:
    /// a format ImageIO cannot size is still captured, bounded by bytes.
    static func pixelSize(of data: Data) -> (pixels: Int, width: Int, height: Int)? {
        let options: [CFString: Any] = [kCGImageSourceShouldCache: false]
        guard let source = CGImageSourceCreateWithData(data as CFData, options as CFDictionary),
              CGImageSourceGetCount(source) > 0,
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let width = properties[kCGImagePropertyPixelWidth] as? Int,
              let height = properties[kCGImagePropertyPixelHeight] as? Int
        else { return nil }
        return (width * height, width, height)
    }

    /// Encode an NSImage as portable image data (PNG preferred).
    static func imageData(for image: NSImage) -> Data? {
        guard let tiff = image.tiffRepresentation else { return nil }
        if let rep = NSBitmapImageRep(data: tiff), let png = rep.representation(using: .png, properties: [:]) {
            return png
        }
        return tiff
    }

    /// Stable hash for text payloads.
    static func hashText(_ string: String) -> String {
        hashData(Data(string.utf8))
    }

    /// Stable hash for binary payloads (SHA-256 hex).
    static func hashData(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}
